services:
  cloudflare-ddns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudflare-ddns
    env_file:
      - .env.dev.local
    restart: unless-stopped
    volumes:
      - cloudflare-ddns-data:/data
  
volumes:
  cloudflare-ddns-data: