services:
  cloudflare-ddns:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: dev
    container_name: cloudflare-ddns-dev
    env_file:
      - .env
    environment:
      - NODE_ENV="dev"
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Código (hot reload en W11)
      - .:/app
      - cloudflare-ddns-data:/data
    command: npm run start:dev
  
volumes:
  cloudflare-ddns-data: